name: Test

on: push

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Build tests
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /property:Configuration=Release eggcpt.sln
        shell: cmd

      - name: Run tests
        run: bin\Release\test.exe
        shell: cmd

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build tests
        run: |
          mkdir test/build
          cd test/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Run tests
        run: ./test/build/test

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Build tests
        run: |
          mkdir test/build
          cd test/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Run tests
        run: ./test/build/test
