name: Test

on: push

jobs:
  test-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build
        run: |
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          msbuild /property:Configuration=Release shell.sln

      - name: Run
        run: bin/Release/test.exe

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir test/build
          cd test/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j 4

      - name: Run
        run: ./test/build/test

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build tests
        run: |
          mkdir test/build
          cd test/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j 4

      - name: Run
        run: ./test/build/test
